version: '3.8'

services:
  mariadb:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - m223_project_mariadb:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret123
      - MYSQL_DATABASE=minitwitter
      - MYSQL_USER=minitwitter
      - MYSQL_PASSWORD=supersecret123
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=supersecret123
    ports:
      - 9200:80

  minitwitter:
    image: mouayad04/minitwitter:v1.0.0
    ports:
      - 4200:4200
    restart: always
    depends_on:
      - mariadb
    environment:
      - DB_NAME=minitwitter
      - DB_USER=root
      - DB_PASSWORD=supersecret123
      - DB_HOST=mariadb

volumes:
  m223_project_mariadb:
