const COMMENT_TABLES = `
CREATE TABLE comment (
  id INT NOT NULL,
  user_id INT NOT NULL,
  comment VARCHAR(255) NOT NULL,
  content INT NOT NULL
);
`;

const LIKES_TABLE = `
CREATE TABLE likes (
  id INT NOT NULL,
  tweet_id INT NOT NULL,
  like INT NOT NULL,
  dislike INT NOT NULL
);
`;

const TWEETS_TABLE = `
CREATE TABLE tweets (
  id INT NOT NULL,
  user_id INT NOT NULL,
  content VARCHAR(255) NOT NULL,
  like INT NOT NULL,
  dislike INT NOT NULL
);
`; 

const USERS_TABLE = `
CREATE TABLE users (
  id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(1) NOT NULL
);
`;
const INSERT = `
INSERT INTO users (id, name, password, role) VALUES
(1, 'admin', '11bcd7d7b9bc2794316b3c5c40c646f747b108c3691ffa9ffc204c00719bd1e6', 'A');
`;

const ALTER_COMMENTS = `
ALTER TABLE comment
  ADD PRIMARY KEY (id),
  ADD KEY user_id (user_id),
  ADD KEY content (content);
`;

const ALTER_LIKES = `
ALTER TABLE likes
  ADD PRIMARY KEY (id),
  ADD KEY user_id (tweet_id),
  ADD KEY dislike (dislike),
  ADD KEY like (like);
`;

const ALTER_TWEETS = `
ALTER TABLE tweets
  ADD PRIMARY KEY (id),
  ADD KEY user_id (user_id),
  ADD KEY like (like),
  ADD KEY dislike (dislike);
`;

const ALTER_USERS = `
ALTER TABLE users
  ADD PRIMARY KEY (id);
`;

const MODIFY_COMMENT = `
ALTER TABLE comment
  MODIFY id INT NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
`;

const MODIFY_LIKES = `
ALTER TABLE likes
  MODIFY id INT NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
`;

const MODIFY_TWEETS = `
ALTER TABLE tweets
  MODIFY id INT NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
`;

const MODIFY_USERS = `
ALTER TABLE users
  MODIFY id INT NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
`;

const CONSTRAINT_COMMENT = `
ALTER TABLE comment
  ADD CONSTRAINT content FOREIGN KEY (content) REFERENCES tweets (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;
`;

const CONSTRAINT_LIKES = `
ALTER TABLE likes
  ADD CONSTRAINT tweet_id FOREIGN KEY (tweet_id) REFERENCES tweets (id) ON DELETE CASCADE ON UPDATE CASCADE;
`;

const CONSTRAINT_TWEETS = `
ALTER TABLE tweets
  ADD CONSTRAINT dislike FOREIGN KEY (dislike) REFERENCES likes (dislike) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT like FOREIGN KEY (like) REFERENCES likes (like) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT tweets_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id),
  ADD CONSTRAINT tweets_ibfk_2 FOREIGN KEY (user_id) REFERENCES users (id);
`;

export { COMMENT_TABLES, LIKES_TABLE, TWEETS_TABLE, USERS_TABLE, INSERT, ALTER_COMMENTS, ALTER_LIKES, ALTER_TWEETS, ALTER_USERS, MODIFY_COMMENT, MODIFY_LIKES, MODIFY_TWEETS, MODIFY_USERS, CONSTRAINT_COMMENT, CONSTRAINT_LIKES, CONSTRAINT_TWEETS };
