const USER_TABLE = `
CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(1) NOT NULL,
    PRIMARY KEY (id)
);
`;

const INSERT_USER = `
INSERT INTO users (id, name, password, role) VALUES
(1, 'admin', '11bcd7d7b9bc2794316b3c5c40c646f747b108c3691ffa9ffc204c00719bd1e6', 'A');
`;

const TWEET_TABLE = `
CREATE TABLE IF NOT EXISTS tweets (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    content VARCHAR(255) NOT NULL,
    like INT NOT NULL,
    dislike INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (like) REFERENCES likes(like) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (dislike) REFERENCES likes(dislike) ON DELETE CASCADE ON UPDATE CASCADE
);
`;

const COMMENT_TABLE = `
CREATE TABLE IF NOT EXISTS comment (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    content INT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (content) REFERENCES tweets(id) ON DELETE CASCADE ON UPDATE CASCADE
);
`;

const LIKE_TABLE = `
CREATE TABLE IF NOT EXISTS likes (
    id INT NOT NULL AUTO_INCREMENT,
    tweet_id INT NOT NULL,
    like INT NOT NULL,
    dislike INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (tweet_id) REFERENCES tweets(id) ON DELETE CASCADE ON UPDATE CASCADE
);
`;

export { USER_TABLE, INSERT_USER, TWEET_TABLE, COMMENT_TABLE, LIKE_TABLE };
