const COMMENT_TABLES = `
CREATE TABLE IF NOT EXISTS comment (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  comment VARCHAR(255) NOT NULL,
  content INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (content) REFERENCES tweets(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
`;

const LIKES_TABLE = `
CREATE TABLE IF NOT EXISTS likes (
  id INT NOT NULL AUTO_INCREMENT,
  tweet_id INT NOT NULL,
  likes INT NOT NULL,
  dislike INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (tweet_id) REFERENCES tweets(id) ON DELETE CASCADE ON UPDATE CASCADE
);
`;

const TWEETS_TABLE = `
CREATE TABLE IF NOT EXISTS tweets (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  content VARCHAR(255) NOT NULL,
  likes INT NOT NULL,
  dislike INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (likes) REFERENCES likes(likes) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (dislike) REFERENCES likes(dislike) ON DELETE CASCADE ON UPDATE CASCADE
);
`; 

const USERS_TABLE = `
CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(1) NOT NULL,
  PRIMARY KEY (id)
);
`;
const INSERT = `
INSERT IGNORE INTO users (id, name, password, role) VALUES
(1, 'admin', '11bcd7d7b9bc2794316b3c5c40c646f747b108c3691ffa9ffc204c00719bd1e6', 'A');
`;


export { COMMENT_TABLES, LIKES_TABLE, TWEETS_TABLE, USERS_TABLE, INSERT };
